### ISSUE TITLE
Contribute GFG solutions 

### ISSUE THREAD

**Issue by onosyoono** [onosyoono/dsm#14]
Contribute competitive programming challenges from GFG.

**Comment by sarthak815** [comment]
I would like to take this up

**Comment by vedant130701** [comment]
I would also like to take this up. Would this entail the practice questions of GFG?

**Comment by onosyoono** [comment]
Yup its cool if you add those as well

**Comment by lucy2512** [comment]
I would like to work on this.

**Comment by Harsh-Modi278** [comment]
Hi @onosyoono, I would like to add solution of https://practice.geeksforgeeks.org/problems/topological-sort/1 in C++. Can you please assign this issue to me?

**Edit**: added problem description

It is a problem under graph category on GeeksForGeeks.

**Description (from the problem link)**:

Given a Directed Acyclic Graph (DAG) with V vertices and E edges, Find any Topological Sorting of that Graph.

You don't need to read input or print anything. Your task is to complete the function topoSort()  which takes the integer V denoting the number of vertices and adjacency list as input parameters and returns an array consisting of a the vertices in Topological order. 

As there are multiple Topological orders possible, you may return any of them. 

Expected Time Complexity: O(V + E).
Expected Auxiliary Space: O(V).

**Constraints**:
2 ≤ V ≤ 104
1 ≤ E ≤ (N*(N-1))/2

PS: [Topological sorting](https://en.wikipedia.org/wiki/Topological_sorting)

**Comment by onosyoono** [comment]
I have assigned you both as well, please provide description before opening pull request

**Comment by Harsh-Modi278** [comment]
> I have assigned you both as well, please provide description before opening pull request

I have added the description in my [previous comment](https://github.com/onosyoono/dsm/issues/14#issuecomment-932986812).

**Comment by lucy2512** [comment]
> I have assigned you both as well, please provide description before opening pull request

I will add the solution for this question:-[https://practice.geeksforgeeks.org/problems/ncr1019/1](url)

**Comment by onosyoono** [comment]
> > I have assigned you both as well, please provide description before opening pull request
> 
> I will add the solution for this question:-[https://practice.geeksforgeeks.org/problems/ncr1019/1](url)

Ok!
