### ISSUE TITLE
Provide Solution for HackerRank python challenges

### ISSUE THREAD

**Issue by onosyoono** [onosyoono/dsm#2]
Please provide implementation details in brief as a comment at the beginning of the file.

**Comment by harsh-singh-rathore** [comment]
Hey I would like to work on this issue

**Comment by Sampai28** [comment]
I have worked on HackerRank questions and I would like to work on this issue.

**Comment by onosyoono** [comment]
You both can work on this! I'll assign to both of you.

**Comment by PSY27** [comment]
Even i would like to contribute

**Comment by onosyoono** [comment]
Ok

**Comment by vedant130701** [comment]
I would like to contribute to this issue. I have done python challenges before.

**Comment by harsh-singh-rathore** [comment]
Will there be an option for cpp?

**Comment by onosyoono** [comment]
Yup I'll open one

**Comment by onosyoono** [comment]
> Yup I'll open one

If you want checkout https://github.com/onosyoono/dsm/issues/4
