### ISSUE TITLE
Hackerrank Cpp Solutions

### ISSUE THREAD

**Issue by onosyoono** [onosyoono/dsm#4]
Please provide C++ solutions for hackerrank issues!

**Comment by harsh-singh-rathore** [comment]
Hey I would like to work on this

**Comment by vedant130701** [comment]
I have done CPP challenges on hackerrank. Currently a 5 star on hackerrank for C++.

**Comment by onosyoono** [comment]
Ok

**Comment by it-is-skywalkerl** [comment]
I would like to work on this. Can I please be assigned to this issue?
